-- Phase 3 — Sales Analysis

-------- Q21. What is the total revenue generated from all completed orders?


SELECT
    SUM(OD.Quantity * OD.UnitPrice) AS TotalRevenue
FROM Orders O
JOIN OrderDetails OD
    ON O.OrderId = OD.OrderId
WHERE O.OrderStatus = 'Completed';


-------- Q22. How many completed orders are there?


SELECT COUNT(*) AS CompletedOrders
FROM Orders
WHERE OrderStatus = 'Completed';


-------- Q23. What is the average order value for completed orders?


SELECT
    SUM(OD.Quantity * OD.UnitPrice)
    / COUNT(DISTINCT O.OrderId) AS AverageOrderValue
FROM Orders O
JOIN OrderDetails OD
    ON O.OrderId = OD.OrderId
WHERE O.OrderStatus = 'Completed';


-------- Q24. What is the total quantity of products sold in completed orders?


SELECT
    SUM(OD.Quantity) AS TotalQuantitySold
FROM Orders O
JOIN OrderDetails OD
    ON O.OrderId = OD.OrderId
WHERE O.OrderStatus = 'Completed';


-------- Q25. What is the revenue generated by each order?


SELECT
    O.OrderId,
    SUM(OD.Quantity * OD.UnitPrice) AS OrderRevenue
FROM Orders O
JOIN OrderDetails OD
    ON O.OrderId = OD.OrderId
WHERE O.OrderStatus = 'Completed'
GROUP BY O.OrderId
ORDER BY OrderRevenue DESC;


---
