-- Phase 4 — Product Analysis

-------- Q26. What is the total revenue generated by each product?


SELECT
    P.ProductId,
    P.ProductName,
    SUM(OD.Quantity * OD.UnitPrice) AS TotalRevenue
FROM Products P
JOIN OrderDetails OD
    ON P.ProductId = OD.ProductId
JOIN Orders O
    ON OD.OrderId = O.OrderId
WHERE O.OrderStatus = 'Completed'
GROUP BY
    P.ProductId,
    P.ProductName
ORDER BY TotalRevenue DESC;


-------- Q27. Which products generated the highest revenue?


SELECT TOP 5
    P.ProductId,
    P.ProductName,
    SUM(OD.Quantity * OD.UnitPrice) AS TotalRevenue
FROM Products P
JOIN OrderDetails OD
    ON P.ProductId = OD.ProductId
JOIN Orders O
    ON OD.OrderId = O.OrderId
WHERE O.OrderStatus = 'Completed'
GROUP BY
    P.ProductId,
    P.ProductName
ORDER BY TotalRevenue DESC;


-------- Q28. How many units of each product were sold?


SELECT
    P.ProductId,
    P.ProductName,
    SUM(OD.Quantity) AS TotalQuantitySold
FROM Products P
JOIN OrderDetails OD
    ON P.ProductId = OD.ProductId
JOIN Orders O
    ON OD.OrderId = O.OrderId
WHERE O.OrderStatus = 'Completed'
GROUP BY
    P.ProductId,
    P.ProductName
ORDER BY TotalQuantitySold DESC;


-------- Q29. What is the total inventory value for each product?


SELECT
    ProductId,
    ProductName,
    Price,
    StockQuantity,
    Price * StockQuantity AS InventoryValue
FROM Products
ORDER BY InventoryValue DESC;


-------- Q30. What is the total inventory value by category?


SELECT
    Category,
    SUM(Price * StockQuantity) AS InventoryValue
FROM Products
GROUP BY Category
ORDER BY InventoryValue DESC;


-------- Q31. Which products have low stock?


SELECT
    ProductId,
    ProductName,
    StockQuantity
FROM Products
WHERE StockQuantity < 20
ORDER BY StockQuantity;


-------- Q32. Which products have never been sold?


SELECT
    P.ProductId,
    P.ProductName
FROM Products P
LEFT JOIN OrderDetails OD
    ON P.ProductId = OD.ProductId
WHERE OD.ProductId IS NULL;


---
